"""
UpTonight output parser
Parses JSON reports generated by UpTonight
"""
import os
import json
from pathlib import Path
from typing import Dict, List, Optional
from logging_config import get_logger

# Initialize logger for this module
logger = get_logger(__name__)

def parse_uptonight_report(file_path: str, report_type: str, catalogue_dir: str) -> Optional[dict]:
    """
    Parse UpTonight JSON report file safely.
    Returns parsed data or None if file doesn't exist or is invalid.
    """
    try:
        # Normalize and confine paths
        catalogue_dir = os.path.normpath(catalogue_dir)
        file_path = os.path.normpath(file_path)

        if not file_path.startswith(os.path.abspath(catalogue_dir)):
            # Path traversal attempt, ignore
            logger.warning(f"Attempted access outside catalogue_dir: {file_path}")
            return None

        if not os.path.exists(file_path):
            return None

        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        if report_type == 'objects':
            return parse_objects_report(data, catalogue_dir)
        elif report_type == 'comets':
            return parse_comets_report(data, catalogue_dir)
        elif report_type == 'bodies':
            return parse_bodies_report(data, catalogue_dir)
        else:
            return {'type': 'unknown', 'raw': data}

    except Exception:
        logger.exception(f"Error parsing UpTonight report {file_path}")
        return None


def parse_objects_report(data: dict, catalogue_dir: str) -> dict:
    """Parse objects (targets) report into list of objects with safe Alttime filenames"""
    objects = []

    if 'id' not in data:
        return {'type': 'objects', 'objects': []}

    num_entries = len(data['id'])

    # Normalize catalogue_dir once
    catalogue_dir = os.path.normpath(catalogue_dir)

    for i in range(num_entries):
        obj = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'id':
                    # Use safe file path generator
                    obj['alttime_file'] = get_alttime_file_name(values[str(i)], catalogue_dir)
                obj[key] = values[str(i)]
        objects.append(obj)

    return {
        'type': 'objects',
        'count': len(objects),
        'objects': objects
    }


def parse_comets_report(data: dict, catalogue_dir: str) -> dict:
    """Parse comets report into list of comets with safe Alttime filenames"""
    comets = []

    if 'target name' not in data:
        return {'type': 'comets', 'comets': []}

    num_entries = len(data['target name'])

    # Normalize catalogue_dir once
    catalogue_dir = os.path.normpath(catalogue_dir)

    for i in range(num_entries):
        comet = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'target name':
                    # Use safe file path generator
                    comet['alttime_file'] = get_alttime_file_name(values[str(i)], catalogue_dir)
                comet[key] = values[str(i)]
        comets.append(comet)

    return {
        'type': 'comets',
        'count': len(comets),
        'comets': comets
    }


def parse_bodies_report(data: dict, catalogue_dir: str) -> dict:
    """Parse bodies (planets/moons) report into a list of bodies with safe Alttime filenames"""

    bodies = []

    if 'target name' not in data:
        return {'type': 'bodies', 'bodies': []}

    num_entries = len(data['target name'])

    # Safe absolute path for catalogue_dir
    base_path = Path(catalogue_dir).resolve()
    if not base_path.exists() or not base_path.is_dir():
        return {'type': 'bodies', 'count': 0, 'bodies': []}

    for i in range(num_entries):
        body = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'target name':
                    # Safe Alttime filename generator
                    alttime_file = get_alttime_file_name(values[str(i)], str(base_path))
                    # Ensure resulting path is confined
                    if alttime_file:
                        file_path = (base_path / alttime_file).resolve()
                        if base_path in file_path.parents or file_path == base_path:
                            body['alttime_file'] = alttime_file
                        else:
                            body['alttime_file'] = None
                body[key] = values[str(i)]
        bodies.append(body)

    return {
        'type': 'bodies',
        'count': len(bodies),
        'bodies': bodies
    }


def get_catalogue_reports(catalogue_dir: str) -> dict:
    """
    Get all available reports for a target
    Returns dictionary with report types and their data
    """

    reports = {}

    base_path = Path(catalogue_dir).resolve()

    if not base_path.exists() or not base_path.is_dir():
        return reports

    report_files = {
        'objects': 'uptonight-report.json',
        'comets': 'uptonight-comets-report.json',
        'bodies': 'uptonight-bodies-report.json',
        'plot': 'uptonight-plot.png'
    }

    for report_type, filename in report_files.items():
        file_path = (base_path / filename).resolve()

        # Ensure file_path stays inside catalogue_dir
        if base_path not in file_path.parents and file_path != base_path:
            continue

        if filename.endswith('.json'):
            parsed = parse_uptonight_report(str(file_path), report_type, str(base_path))
            if parsed:
                reports[report_type] = parsed
        elif file_path.exists():
            reports[report_type] = {
                'available': True,
                'path': filename
            }

    return reports


def format_value(key: str, value) -> str:
    """Format values for display"""
    if value is None or value == '':
        return 'N/A'
    
    # Handle numeric formatting
    if isinstance(value, (int, float)):
        # Foto is a percentage
        if key == 'foto':
            return f"{value * 100:.1f}%"
        # Magnitudes
        elif key in ['mag', 'visual magnitude', 'absolute magnitude']:
            return f"{value:.2f}"
        # Coordinates
        elif key in ['right ascension', 'declination', 'altitude', 'azimuth']:
            return f"{value:.2f}°"
        # Distances
        elif 'distance' in key.lower():
            return f"{value:.3f} AU"
        # Sizes
        elif key == 'size':
            return f"{value:.1f}'"
        else:
            return str(value)
    
    return str(value)


def sanitize_alttime_target_name(name: str) -> str:
    """Sanitize target name for Alttime compatibility"""
    sanitized = name.lower().replace(' ', '-').replace('/', '-').replace('\\', '-')
    return sanitized


def get_alttime_file_name(target_name: str, catalogue_dir: str) -> str:
    """
    Generate Alttime-compatible file name from target name.
    Return file name if exists, else empty string.
    """
    sanitized = sanitize_alttime_target_name(target_name)

    # Normalize path and confine to catalogue_dir
    filename = f"uptonight-alttime-{sanitized}.png"
    file_path = os.path.normpath(os.path.join(catalogue_dir, filename))

    if not file_path.startswith(os.path.abspath(catalogue_dir)):
        # Path traversal attempt, ignore
        return ""

    if os.path.exists(file_path):
        return filename
    else:
        return ""