"""
UpTonight output parser
Parses JSON reports generated by UpTonight
"""
import os
import json
from pathlib import Path
import re
from typing import Dict, List, Optional
from logging_config import get_logger

# Initialize logger for this module
logger = get_logger(__name__)


def _resolve_catalogue_dir(catalogue_dir: str) -> Optional[Path]:
    """Resolve and validate a catalogue directory path."""
    try:
        base_path = Path(catalogue_dir).resolve()
    except (TypeError, ValueError, RuntimeError):
        return None

    if not base_path.exists() or not base_path.is_dir():
        return None

    return base_path


def _resolve_path_within(base_path: Path, candidate_path: str) -> Optional[Path]:
    """Resolve a candidate path and ensure it stays within base_path."""
    try:
        candidate = Path(candidate_path)
        resolved = (base_path / candidate).resolve() if not candidate.is_absolute() else candidate.resolve()
        resolved.relative_to(base_path)
        return resolved
    except (TypeError, ValueError, RuntimeError):
        return None

def parse_uptonight_report(file_path: str, report_type: str, catalogue_dir: str) -> Optional[dict]:
    """
    Parse UpTonight JSON report file safely.
    Returns parsed data or None if file doesn't exist or is invalid.
    """
    try:
        base_path = _resolve_catalogue_dir(catalogue_dir)
        if not base_path:
            return None

        expected_files = {
            'objects': 'uptonight-report.json',
            'comets': 'uptonight-comets-report.json',
            'bodies': 'uptonight-bodies-report.json'
        }

        if report_type in expected_files:
            safe_file_path = _resolve_path_within(base_path, expected_files[report_type])
        else:
            safe_file_path = _resolve_path_within(base_path, Path(file_path).name)

        if not safe_file_path:
            # Path traversal attempt, ignore
            logger.warning(f"Attempted access outside catalogue_dir: {file_path}")
            return None

        if not safe_file_path.exists() or not safe_file_path.is_file():
            return None

        with safe_file_path.open('r', encoding='utf-8') as f:
            data = json.load(f)

        if report_type == 'objects':
            return parse_objects_report(data, str(base_path))
        elif report_type == 'comets':
            return parse_comets_report(data, str(base_path))
        elif report_type == 'bodies':
            return parse_bodies_report(data, str(base_path))
        else:
            return {'type': 'unknown', 'raw': data}

    except Exception:
        logger.exception(f"Error parsing UpTonight report {file_path}")
        return None


def parse_objects_report(data: dict, catalogue_dir: str) -> dict:
    """Parse objects (targets) report into list of objects with safe Alttime filenames"""
    objects = []

    if 'id' not in data:
        return {'type': 'objects', 'objects': []}

    num_entries = len(data['id'])

    base_path = _resolve_catalogue_dir(catalogue_dir)
    safe_catalogue_dir = str(base_path) if base_path else ""

    for i in range(num_entries):
        obj = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'id':
                    # Use safe file path generator
                    obj['alttime_file'] = get_alttime_file_name(values[str(i)], safe_catalogue_dir)
                obj[key] = values[str(i)]
        objects.append(obj)

    return {
        'type': 'objects',
        'count': len(objects),
        'objects': objects
    }


def parse_comets_report(data: dict, catalogue_dir: str) -> dict:
    """Parse comets report into list of comets with safe Alttime filenames"""
    comets = []

    if 'target name' not in data:
        return {'type': 'comets', 'comets': []}

    num_entries = len(data['target name'])

    base_path = _resolve_catalogue_dir(catalogue_dir)
    safe_catalogue_dir = str(base_path) if base_path else ""

    for i in range(num_entries):
        comet = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'target name':
                    # Use safe file path generator
                    comet['alttime_file'] = get_alttime_file_name(values[str(i)], safe_catalogue_dir)
                comet[key] = values[str(i)]
        comets.append(comet)

    return {
        'type': 'comets',
        'count': len(comets),
        'comets': comets
    }


def parse_bodies_report(data: dict, catalogue_dir: str) -> dict:
    """Parse bodies (planets/moons) report into a list of bodies with safe Alttime filenames"""

    bodies = []

    if 'target name' not in data:
        return {'type': 'bodies', 'bodies': []}

    num_entries = len(data['target name'])

    base_path = _resolve_catalogue_dir(catalogue_dir)
    if not base_path:
        return {'type': 'bodies', 'count': 0, 'bodies': []}

    safe_catalogue_dir = str(base_path)

    for i in range(num_entries):
        body = {}
        for key, values in data.items():
            if str(i) in values:
                if key == 'target name':
                    # Use safe file path generator
                    body['alttime_file'] = get_alttime_file_name(values[str(i)], safe_catalogue_dir)
                body[key] = values[str(i)]
        bodies.append(body)

    return {
        'type': 'bodies',
        'count': len(bodies),
        'bodies': bodies
    }


def get_catalogue_reports(catalogue_dir: str) -> dict:
    """
    Get all available reports for a target
    Returns dictionary with report types and their data
    """

    reports = {}

    base_path = _resolve_catalogue_dir(catalogue_dir)
    if not base_path:
        return reports

    report_files = {
        'objects': 'uptonight-report.json',
        'comets': 'uptonight-comets-report.json',
        'bodies': 'uptonight-bodies-report.json',
        'plot': 'uptonight-plot.png'
    }

    for report_type, filename in report_files.items():
        if filename.endswith('.json'):
            parsed = parse_uptonight_report(filename, report_type, str(base_path))
            if parsed:
                reports[report_type] = parsed
        else:
            file_path = _resolve_path_within(base_path, filename)
            if not file_path or not file_path.exists():
                continue
            reports[report_type] = {
                'available': True,
                'path': filename
            }

    return reports


def format_value(key: str, value) -> str:
    """Format values for display"""
    if value is None or value == '':
        return 'N/A'
    
    # Handle numeric formatting
    if isinstance(value, (int, float)):
        # Foto is a percentage
        if key == 'foto':
            return f"{value * 100:.1f}%"
        # Magnitudes
        elif key in ['mag', 'visual magnitude', 'absolute magnitude']:
            return f"{value:.2f}"
        # Coordinates
        elif key in ['right ascension', 'declination', 'altitude', 'azimuth']:
            return f"{value:.2f}°"
        # Distances
        elif 'distance' in key.lower():
            return f"{value:.3f} AU"
        # Sizes
        elif key == 'size':
            return f"{value:.1f}'"
        else:
            return str(value)
    
    return str(value)


def sanitize_alttime_target_name(name: str) -> str:
    """
    Sanitize a target name to be a safe filename.
    Preserves letters, numbers, dots, dashes, underscores, and parentheses.
    """
    name = name.lower()
    # autoriser a-z, 0-9, ., _, -, (, )
    name = re.sub(r'[^a-z0-9._\-\(\)]', '-', name)
    name = re.sub(r'\.{2,}', '.', name)    # collapse multiple dots
    name = name.strip('-.')                 # trim leading/trailing dash/dot
    return name or "target"


def get_alttime_file_name(target_name: str, catalogue_dir: str) -> str:
    """
    Generate Alttime-compatible file name from target name.
    Return file name if exists, else empty string.
    """
    sanitized = sanitize_alttime_target_name(target_name)
    base_path = _resolve_catalogue_dir(catalogue_dir)
    if not base_path:
        return ""

    filename = f"uptonight-alttime-{sanitized}.png"
    file_path = _resolve_path_within(base_path, filename)
    if not file_path:
        return ""

    if file_path.exists() and file_path.is_file():
        return filename
    else:
        return ""