title: "[Data]: "
body:
  - type: input
    id: source
    attributes:
      label: Data source

  - type: textarea
    id: issue
    attributes:
      label: Issue

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion