title: "[Idea]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution