name: Documentation Improvement
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - Installation Guide
        - Quick Start Guide
        - Update Guide
        - Release Guide
        - Code Comments
        - API Documentation
        - Configuration Examples
        - Troubleshooting
        - Other
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing in the current documentation?
      placeholder: The current documentation doesn't explain...
    validations:
      required: true
      
  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs improvement? (file path, URL, or section name)
      placeholder: e.g., docs/1.INSTALLATION.md, README.md section "Quick Start"
    validations:
      required: false
      
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should include...
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the documentation improvement here.
    validations:
      required: false
